FROM rasa/rasa:latest

USER root
WORKDIR /chatbot
COPY . /chatbot

RUN rasa train

USER 1001

ENTRYPOINT ["rasa"]
CMD ["run", "--enable-api", "--cors", "*", "--port", "$PORT", "--endpoints", "endpoints.yml"]