FROM rasa/rasa:latest

USER root
WORKDIR /chatbot
COPY . /chatbot

RUN rasa train

# Set environment variable to suppress SQLAlchemy warning
ENV SQLALCHEMY_SILENCE_UBER_WARNING=1

USER 1001

# Use shell form of CMD to allow variable expansion
CMD rasa run --enable-api --cors "*" --port ${PORT_RASA:-5005} --endpoints endpoints.yml