
services:
  - type: web
    name: rasa-chatbot
    env: docker
    dockerfilePath: ./dockerfile.rasa
    plan: free
    healthCheckPath: /

  - type: web
    name: rasa-actions
    env: docker
    dockerfilePath: ./dockerfile.customActions
    plan: free
    healthCheckPath: /
